/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeTest */

#ifndef _Included_nativeTest
#define _Included_nativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeTest
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeTest_nativePrint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
